// Package cq is the code-quality judge's core: language detection, comment blanking, secret
// redaction, the fault catalogue, the Jev wire, scoring, and the tree walk. It touches the world
// only through the FS, Judge and Cache interfaces, so the plugin binds it to the host's
// hostcalls and cmd/cqvalidate binds it to the local disk and Jev directly.
package cq

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
)

// annex_l.json is Annex L of the design (the language table), extracted verbatim.
//
//go:embed annex_l.json
var annexJSON []byte

// Lang is one row of the language table.
type Lang struct {
	Key          string
	Include      *regexp.Regexp
	Shebang      *regexp.Regexp
	ExcludeDirs  *regexp.Regexp
	ExcludeFiles *regexp.Regexp
	Generated    *regexp.Regexp
	Tests        *regexp.Regexp
	LineComment  string
	Blocks       [][2]string
}

// Table is the parsed language table plus its global exclusions.
type Table struct {
	Langs       map[string]*Lang
	order       []string
	GlobalDirs  *regexp.Regexp
	GlobalFiles *regexp.Regexp
	Binary      *regexp.Regexp
}

// specialFilenames name a language by the whole base name; each value is a key of the table.
var specialFilenames = map[string]string{
	"Dockerfile": "dockerfile", "Makefile": "makefile", "GNUmakefile": "makefile", "CMakeLists.txt": "cmake",
	"Rakefile": "ruby", "Gemfile": "ruby",
}

// SecretNamed files are never read.
var SecretNamed = regexp.MustCompile(`(?i)^(\.env(\..*)?|.*\.(pem|key|p12|pfx)|id_[a-z0-9]+|.*credentials.*\.json)$`)

var generatedGeneric = regexp.MustCompile(`(?i)(code generated .* do not edit|do not edit|@generated\b|<auto-generated|auto-?generated|automatically generated|this (file|code) (was|is) generated)`)

// languages whose extensions others share; they are tried last.
var ambiguous = map[string]bool{"c": true, "cpp": true, "objc": true, "matlab": true, "verilog": true, "fsharp": true, "perl": true, "r": true}

// LoadTable parses the embedded language table.
func LoadTable() (*Table, error) {
	var a struct {
		Global struct {
			ExcludeDirs  string `json:"exclude_dirs"`
			ExcludeFiles string `json:"exclude_files"`
			Binary       string `json:"exclude_binary_media_ext"`
		} `json:"global"`
		Languages map[string]struct {
			Include   string `json:"include_files"`
			Shebangs  string `json:"shebangs"`
			ExclDirs  string `json:"exclude_dirs"`
			ExclFiles string `json:"exclude_files"`
			Generated string `json:"generated_signature"`
			Tests     string `json:"test_patterns"`
			Comments  *struct {
				Line     string   `json:"line"`
				Block    []string `json:"block"`
				BlockAlt []string `json:"block_alt"`
			} `json:"comment_syntax"`
		} `json:"languages"`
	}
	if err := json.Unmarshal(annexJSON, &a); err != nil {
		return nil, fmt.Errorf("language table: %w", err)
	}
	var err error
	re := func(s string) *regexp.Regexp {
		if s == "" || err != nil {
			return nil
		}
		r, e := regexp.Compile(s)
		if e != nil {
			err = fmt.Errorf("language table pattern %q: %w", s, e)
		}
		return r
	}
	t := &Table{Langs: map[string]*Lang{}, GlobalDirs: re(a.Global.ExcludeDirs), GlobalFiles: re(a.Global.ExcludeFiles), Binary: re(a.Global.Binary)}
	for k, v := range a.Languages {
		L := &Lang{Key: k, Include: re(v.Include), Shebang: re(v.Shebangs), ExcludeDirs: re(v.ExclDirs),
			ExcludeFiles: re(v.ExclFiles), Generated: re(v.Generated), Tests: re(v.Tests)}
		if c := v.Comments; c != nil {
			L.LineComment = c.Line
			for _, b := range [][]string{c.Block, c.BlockAlt} {
				if len(b) == 2 && b[0] != "" {
					L.Blocks = append(L.Blocks, [2]string{b[0], b[1]})
				}
			}
		}
		t.Langs[k] = L
		t.order = append(t.order, k)
	}
	if err != nil {
		return nil, err
	}
	sort.Slice(t.order, func(i, j int) bool {
		ai, aj := ambiguous[t.order[i]], ambiguous[t.order[j]]
		if ai != aj {
			return !ai
		}
		return t.order[i] < t.order[j]
	})
	return t, nil
}

// Detect names a file's language from its path and first bytes, or "" when it is not a language
// the table knows.
func (t *Table) Detect(rel string, head []byte) string {
	base := path.Base(rel)
	if k, ok := specialFilenames[base]; ok && t.Langs[k] != nil {
		return k
	}
	h := string(head)
	ext := ""
	if i := strings.LastIndexByte(base, '.'); i >= 0 {
		ext = strings.ToLower(base[i+1:])
	}
	switch ext {
	case "h":
		if strings.Contains(h, "@interface") || strings.Contains(h, "#import") {
			return "objc"
		}
		return "c"
	case "m":
		if strings.Contains(h, "@interface") || strings.Contains(h, "#import") {
			return "objc"
		}
		return "matlab"
	}
	for _, k := range t.order {
		if L := t.Langs[k]; L.Include != nil && L.Include.MatchString(base) {
			return k
		}
	}
	if strings.HasPrefix(h, "#!") {
		first := h
		if i := strings.IndexByte(h, '\n'); i >= 0 {
			first = h[:i]
		}
		for _, k := range t.order {
			if L := t.Langs[k]; L.Shebang != nil && L.Shebang.MatchString(first) {
				return k
			}
		}
	}
	return ""
}

// IsGenerated reports a generated-file marker in the first 40 lines.
func (t *Table) IsGenerated(lang string, text []byte) bool {
	head := string(text)
	n := 0
	for i := 0; i < len(head); i++ {
		if head[i] == '\n' {
			if n++; n == 40 {
				head = head[:i]
				break
			}
		}
	}
	if L := t.Langs[lang]; L != nil && L.Generated != nil && L.Generated.MatchString(head) {
		return true
	}
	return generatedGeneric.MatchString(head)
}

// IsTest reports a test file by the language's test patterns (matched against the base name and
// the slash-rooted relative path).
func (t *Table) IsTest(lang, rel string) bool {
	L := t.Langs[lang]
	if L == nil || L.Tests == nil {
		return false
	}
	return L.Tests.MatchString(path.Base(rel)) || L.Tests.MatchString("/"+rel)
}
